### PR TITLE
Add readme md (#10)

### PR DESCRIPTION
**Pull request by flexconstructor**
- bump up project version
- add keywords
- package new version of openvidu-browser

### CODE REVIEW

**Comment by flexconstructor** [comment]
@tyranron ,

FCM:

```
Prepare 2.7.0-r2 version of openvidu-browser (#10)

- add readme file
- bump up project version
- add keywords
- package new version of openvidu-browser
```

**Comment by tyranron** [comment]
@flexconstructor well, I think @alexlapa is able to review such PRs for this project in future.

**Review by tyranron — APPROVED** [review]

**Comment by flexconstructor** [comment]
@tyranron ,

>well, I think @alexlapa is able to review such PRs for this project in future.

The choice of you as a reviewer is caused by the work schedule of @alexlapa . We would have had to wait a whole day before it began.

**Comment by tyranron** [comment]
@flexconstructor well, that problem should be addressed inside your team with @alexlapa. My resource is too limited, unfortunately.

**Pull request merged**
